---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Entrada dos dados

```{r}
library(readxl)
dados <- read_excel("data-raw/vitaminaD.xls")
dados <- dados |>
  janitor::clean_names()
```


Adição de novos dados.

```{r}
novos <- read_excel("data-raw/densidade mineral ossea dos animais do artigo.xlsx")
novos <- novos |>
  janitor::clean_names()
dados <- dplyr::left_join(dados, novos, by="animal_1") |> 
  dplyr::select(-animal_2.y)
```

Análise não paramétrica (pois foram observados grande assimetria nos valores das variáveis contínuas), então optou-se pela abordagem não paramétrica para todo o grupo de variáveis estudadas.

```{r}
da <- dados |> 
  dplyr::select(
    percent_gordura,
    idade,
    peso,
    vit_d,
    bmc_massa_mineral_ossea,
    densidade_mineral_ossea
  )
```


```{r}
for(i in 1:length(da)){
  print("============================")
  print(names(da[i]))
  print("============================")
  y <- da[,i]
  print(agricolae::kruskal(y, dados$tem_tumor,
                     console = TRUE))
}
```




